name: Run Strategies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-strategies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run strategy 1
        run: |
          python src/strategy/strat1.py
      
      - name: Run strategy 2
        run: |
          python src/strategy/strat2.py

      - name: Run strategy 3
        run: |
          python src/strategy/strat3.py
